### ISSUE TITLE
`table` drawing issue

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#571]
It seems that there are cases where table drawing is losing some of the input:

engine-q:
```
〉cat ./utf16.ini | decode utf-16 | lines --skip-empty
╭───┬─────────────────────────────────────────────────────────────────╮
│ 0 │                                                                 │
                                               │
 │2 │ LocalizedResourceName=@%SystemRoot%\system32\shell32.dll,-21779
               │SystemRoot%\system32\shell32.dll,-12688
            │ource=%SystemRoot%\system32\imageres.dll,-113
                      │oot%\system32\shell32.dll
                                                  │
│ 7 │                                                                 │
╰───┴─────────────────────────────────────────────────────────────────╯
```

compare nushell:
```
───┬─────────────────────────────────────────────────────────────────
 0 │                                                                 
 1 │ [.ShellClassInfo]                                               
 2 │ LocalizedResourceName=@%SystemRoot%\system32\shell32.dll,-21779 
 3 │ InfoTip=@%SystemRoot%\system32\shell32.dll,-12688               
 4 │ IconResource=%SystemRoot%\system32\imageres.dll,-113            
 5 │ IconFile=%SystemRoot%\system32\shell32.dll                      
 6 │ IconIndex=-236                                                  
───┴─────────────────────────────────────────────────────────────────

```

**Comment by fdncred** [comment]
very interesting. BTW, this is one of the reasons I want `into binary` to work with text files.

I'm trying to find odd characters that would mess up the table but none are jumping out yet.

<img width="722" alt="Screen Shot 2021-12-26 at 1 18 10 PM" src="https://user-images.githubusercontent.com/343840/147417936-e128dd5f-b783-4b26-8edc-ead4a67c2dca.png">

<img width="898" alt="Screen Shot 2021-12-26 at 1 17 09 PM" src="https://user-images.githubusercontent.com/343840/147417911-f1eb766b-706d-476a-8758-d28406d3c7d7.png">

<img width="807" alt="Screen Shot 2021-12-26 at 1 19 35 PM" src="https://user-images.githubusercontent.com/343840/147417973-18f93846-5fcf-464e-8ab1-6b45a78e10eb.png">

also, `open` doesn't handle this either, but in a different way.

# OH WAIT #
could it be the left and right brackets `[.ShellClassInfo] `?

**Comment by jntrnr** [comment]
@fdncred it'll work with open but you need to do `open ./utf16.ini | decode utf-16`

Hmm, I'm trying your theory of the brackets with a smaller example and so far can't find a repro, but you might be on to something. Maybe it's a combination of things.

**Comment by jntrnr** [comment]
Found a small repro:

```
〉$"[.ShellClassInfo]|(char -u d)and another" | split row "|" | table
╭───┬───────────────────╮
│ 0 │ [.ShellClassInfo] │
and another       │
╰───┴───────────────────╯
```

Looks like the `\r` is getting left in the string by the `lines` command when it should be getting removed, and that's throwing off the table.

**Comment by fdncred** [comment]
I'm so confused.

```
〉$"[.ShellClassInfo]|(char -u d)and another"
and anothersInfo]|
```

**Comment by fdncred** [comment]
oh ya, (char -u d) is \r

**Comment by jntrnr** [comment]
The question I guess then is, if you're on linux and do `lines` on text that's coming in with Windows line endings, so we split the Windows line endings? or should have to do `lines` and trim the lines?

**Comment by jntrnr** [comment]
Ahh, I'm going to try a bit of autodetection logic in `lines` to see if that'll help.

**Comment by fdncred** [comment]
I can see a couple options here.
1. some heuristic that auto-detects line endings by looking at X amount of lines, up to the entire file if necessary?
2. specify the `lines` split mechanism i.e. use \r, \n or \r\n

**Comment by jntrnr** [comment]
yeah, I just put a PR together for option 1 to see how works in practice

**Comment by eggcaker** [comment]
is this issue related to mine open a csv file engine-q crashed issue ?

**Comment by jntrnr** [comment]
@eggcaker I'm not sure - is the csv something you can share?

**Comment by eggcaker** [comment]
[test.csv](https://github.com/nushell/engine-q/files/7779331/test.csv)

**Comment by jntrnr** [comment]
@eggcaker - that seems to work okay in the latest engine-q if you do:

```
open ~/Downloads/test.csv
```

**Comment by eggcaker** [comment]
[test2.csv](https://github.com/nushell/engine-q/files/7780469/test2.csv)

@jntrnr can you try this file ?

**Comment by jntrnr** [comment]
Should be fixed by https://github.com/nushell/engine-q/pull/589

**Comment by fdncred** [comment]
still doesn't work for me and the span must be whacked (or something) given the odd error message.

```
〉open ./utf16.ini | decode utf-16 | str trim | lines
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.1.0/nu-protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[Host Environment Variables:1:1]
 1 │ "CARGO"="/Users/fdncred/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo"
   · ▲
   · ╰── Could not load ini: Custom("INI syntax error: variable assignment missing '='")
 2 │ "CARGO_HOME"="/Users/fdncred/.cargo"
   ╰────
```

**Comment by fdncred** [comment]
closing again because the same statement with `open -r` works.
